FROM nginx:1.25
RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

#Адрес для клонирования
ARG url=https://github.com/kaser137/test.git

ARG path=test
#ARG pathproject=test/.git

#Ветка по умолчанию
ARG branch=master

WORKDIR alex

RUN if [ -d $path/.git ]; then cd $path && git pull; elif [ -d $path ]; then cd $path && (shopt -s dotglob && rm -rf *) &&  git clone  $url -b $branch .; else git clone  $url -b $branch; fi
#RUN cp ./test/aa.py .
#RUN echo '#!/bin/bash' > init.sh
#RUN echo 'if [ -d '$path'/.git ]; then cd '$path' && git pull; elif [ -d '$path' ]; then cd '$path' && (shopt -s dotglob && rm -rf *) &&  git clone  '$url' -b '$branch' .; else mkdir '$path' && cd '$path' && git clone  '$url' -b '$branch' .; fi' >> init.sh
#RUN echo sleep 3600 >> init.sh
#RUN chmod 777 init.sh
RUN rm /etc/nginx/conf.d/default.conf
#RUN cp ./$path/nginx/test.conf /etc/nginx/conf.d
#COPY ./test.conf  /etc/nginx/conf.d
RUN cp ./$path/nginx/test.conf /etc/nginx/conf.d/
#RUN cd ./$path/nginx/
#ENTRYPOINT ["sleep", "3600"]